name: "Check Issue Label"

description: 'Checks if an issue has the "internal" label and sets outputs or prints messages accordingly.'

inputs:
  token:
    description: "GitHub token to access the issue information"
    required: true
  issue_number:
    description: "The number of the issue to check"
    required: true
  openai_api_key:
    description: "OpenAI API key to use for the triager"
    required: true

outputs:
  has-internal:
    description: 'True if the issue has the "internal" label, otherwise false'
    value: ${{ steps.check_internal.outputs.has-internal }}

runs:
  using: "composite"
  steps:
    - name: Set variables
      run: |
        echo "INTERNAL_LABEL=internal" >> $GITHUB_ENV
      shell: bash
    - name: Fetch issue labels
      id: fetch-facts
      run: |
        repo="${{ github.repository }}"
        issue_info=$(curl -s -H "Authorization: token ${{ inputs.token }}" \
                "https://api.github.com/repos/$repo/issues/${{ inputs.issue_number }}")
        labels=$(echo "$issue_info" | jq -r '.labels[] | select(.name == "${{ env.INTERNAL_LABEL }}") | .name')
        state=$(echo "$issue_info" | jq -r '.state')

        echo "Issue number: ${{ inputs.issue_number }}"
        echo "Fetched labels: $labels"
        echo "Fetched state: $state"

        echo "labels=$labels" >> $GITHUB_OUTPUT
        echo "state=$state" >> $GITHUB_OUTPUT
      shell: bash

    - name: if state is not open
      id: check-state
      run: |
        if [ "${{ steps.fetch-facts.outputs.state }}" = "open" ]; then
          echo "should_triage=true" >> $GITHUB_OUTPUT
        else
          echo "The issue is not open or has the internal label. Finishing the job."
          echo "should_triage=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: actions/setup-go@v5
      if: steps.check-state.outputs.should_triage == 'true'
      with:
        go-version: "1.22.3"
    - name: Run Triager
      if: steps.check-state.outputs.should_triage == 'true'
      id: triager
      run: |
        output=$(go run ${{ github.action_path }}/pkg/cmd/triager-fine-tuned/triager-fine-tuned.go -issueId ${{ inputs.issue_number }} -repo ${{ github.repository }})
        echo "triager_output=$output" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}

    - name: Use output
      if: steps.check-state.outputs.should_triage == 'true'
      run: echo "${{ steps.triager.outputs.triager_output }}"
      shell: bash
