name: "Check Issue Label"

description: 'Checks if an issue has the "internal" label and sets outputs or prints messages accordingly.'

inputs:
  token:
    description: "GitHub token to access the issue information"
    required: true
  issue_number:
    description: "The number of the issue to check"
    required: true

outputs:
  has-internal:
    description: 'True if the issue has the "internal" label, otherwise false'
    value: ${{ steps.check_internal.outputs.has-internal }}

runs:
  using: "composite"
  steps:
    - name: Fetch issue labels
      id: fetch_labels
      run: |
        repo="${{ github.repository }}"
        labels=$(curl -s -H "Authorization: token ${{ inputs.token }}" \
                "https://api.github.com/repos/$repo/issues/${{ inputs.issue_number }}" \
              | jq -r '.labels | map(.name) | join(",")')
        echo "Issue number: ${{ inputs.issue_number }}"
        echo "Api url: https://api.github.com/repos/$repo/issues/${{ inputs.issue_number }}"
        echo "Repo name: $repo"
        echo "Fetched labels: $labels"
        echo "::set-output name=labels::$labels"
      shell: bash

    - name: Check for "internal" label
      id: check_internal
      run: |
        labels="${{ steps.fetch_labels.outputs.labels }}"
        if echo "$labels" | grep -q "internal"; then
          echo "The 'internal' label was found."
          echo "::set-output name=has-internal::true"
        else
          echo "hello world"
          echo "::set-output name=has-internal::false"
        fi
      shell: bash
